"use client";

// Sim camera overlay — renders the 8 Unity simulation cameras (cam0..cam7)
// as bright green dots so they're visually distinct from the gray HK gov
// cameras served by CamerasLayer.
//
// Data comes from public/data/sim-cameras.geojson, generated by
// Orgs/system4-unity-simulation/Tools/export_camera_geojson.py from the
// Unity scene's hk_setup.json. See that script's header for the
// Unity→WGS84 anchor decision.

import { useEffect, useRef } from "react";
import type maplibregl from "maplibre-gl";
import maplibreglRuntime from "maplibre-gl";
import { useMapInstance } from "@/lib/map-context";
import { useApp } from "@/lib/store";

const SOURCE_ID = "sim-cameras";
const CIRCLE_LAYER_ID = "sim-cameras-circle";
const GEOJSON_URL = "/data/sim-cameras.geojson";

// MediaMTX base URL serving the Unity-published HLS preview pages
// (http://<host>:8888/cam0..cam7). Override at build time via
// NEXT_PUBLIC_SIM_PREVIEW_BASE for non-localhost demo machines.
const SIM_PREVIEW_BASE =
  process.env.NEXT_PUBLIC_SIM_PREVIEW_BASE ?? "http://localhost:8888";

const EMPTY_FC: GeoJSON.FeatureCollection = {
  type: "FeatureCollection",
  features: [],
};

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    c === "&"
      ? "&amp;"
      : c === "<"
        ? "&lt;"
        : c === ">"
          ? "&gt;"
          : c === '"'
            ? "&quot;"
            : "&#39;",
  );
}

function popupHtml(props: Record<string, unknown>): string {
  const key = typeof props.source_key === "string" ? props.source_key : "";
  const alt = typeof props.alt_m === "number" ? Math.round(props.alt_m) : null;
  const fov = typeof props.fov === "number" ? props.fov : null;
  const hdg =
    typeof props.heading_deg === "number" ? Math.round(props.heading_deg) : null;
  const ux = typeof props.unity_x === "number" ? Math.round(props.unity_x) : null;
  const uy = typeof props.unity_y === "number" ? Math.round(props.unity_y) : null;
  const uz = typeof props.unity_z === "number" ? Math.round(props.unity_z) : null;

  // CAM-0 .. CAM-7 — the surveillance-monitor label form.
  const camId = key
    ? key.toUpperCase().replace(/^CAM/, "CAM-")
    : "CAM-?";

  // Snapshot timestamp at popup-open. We don't tick it (MapLibre popups
  // are innerHTML, not React) — a frozen open-time is honest about what
  // "live" means here: the iframe is the live part.
  const ts = new Date()
    .toISOString()
    .replace("T", " ")
    .replace(/\.\d+Z$/, " UTC");

  // key is "cam0".."cam7" — exactly what MediaMTX uses as the path segment.
  // The HLS reader page handles its own playback; we just iframe it. If
  // MediaMTX is down the iframe is a 404 page; the "open feed" link in
  // the footer lets the operator pop it out to debug.
  const previewUrl = key
    ? `${SIM_PREVIEW_BASE}/${encodeURIComponent(key)}`
    : null;
  // Permissions-Policy: "fullscreen" without an origin list defaults to
  // 'self' — i.e. same-origin only. The MediaMTX iframe is served from
  // localhost:8888 while the dashboard is on :3199, so we must explicitly
  // grant cross-origin with "*" or its fullscreen button silently does
  // nothing. Same for autoplay so the HLS video starts without a click.
  // The trailing ⛶ overlay is a parent-side shortcut: it requestFullscreen()s
  // the iframe element from the parent, which works regardless of the
  // iframe's policy.
  const feed = previewUrl
    ? `<iframe src="${escapeHtml(previewUrl)}" allow="autoplay *; fullscreen *" allowfullscreen referrerpolicy="no-referrer"></iframe>
       <button class="sim-cam-popup__fs" type="button" aria-label="Fullscreen">⛶</button>`
    : `<div class="cam-popup__fallback">No feed URL</div>`;

  const altCell = alt !== null ? `${alt}<span style="color:#64748b">m</span>` : "—";
  const fovCell = fov !== null ? `${fov}<span style="color:#64748b">°</span>` : "—";
  const hdgCell = hdg !== null ? `${hdg}<span style="color:#64748b">°</span>` : "—";

  const unityFooter =
    ux !== null && uy !== null && uz !== null
      ? `<span>UNITY ${ux},${uy},${uz}</span>`
      : "<span></span>";
  const openLink = previewUrl
    ? `<a href="${escapeHtml(previewUrl)}" target="_blank" rel="noreferrer">open ↗</a>`
    : "";

  return `
    <div class="sim-cam-popup">
      <div class="sim-cam-popup__bar">
        <span class="sim-cam-popup__id">${escapeHtml(camId)}</span>
        <span class="sim-cam-popup__live">LIVE</span>
        <span class="sim-cam-popup__rec">REC</span>
      </div>
      <div class="sim-cam-popup__feed">${feed}</div>
      <div class="sim-cam-popup__telemetry">
        <div><span class="label">Alt</span><span class="value">${altCell}</span></div>
        <div><span class="label">FOV</span><span class="value">${fovCell}</span></div>
        <div><span class="label">Hdg</span><span class="value">${hdgCell}</span></div>
      </div>
      <div class="sim-cam-popup__footer">
        ${unityFooter}
        <span>${escapeHtml(ts)}</span>
        ${openLink}
      </div>
    </div>
  `;
}

export default function SimCamerasLayer() {
  const map = useMapInstance();
  const dataRef = useRef<GeoJSON.FeatureCollection>(EMPTY_FC);
  const popupRef = useRef<maplibregl.Popup | null>(null);

  // One-shot fetch of the static seed. The file is tiny (~8 features) and
  // rewritten only when the exporter re-runs, so we don't poll.
  useEffect(() => {
    let cancelled = false;
    fetch(GEOJSON_URL, { cache: "no-store" })
      .then((r) => (r.ok ? r.json() : EMPTY_FC))
      .then((fc: GeoJSON.FeatureCollection) => {
        if (cancelled) return;
        dataRef.current = fc;
        const src = map?.getSource(SOURCE_ID) as
          | maplibregl.GeoJSONSource
          | undefined;
        src?.setData(fc);
      })
      .catch(() => {
        /* keep EMPTY_FC — never break the dashboard on a missing seed */
      });
    return () => {
      cancelled = true;
    };
  }, [map]);

  useEffect(() => {
    if (!map) return;

    if (!map.getSource(SOURCE_ID)) {
      map.addSource(SOURCE_ID, {
        type: "geojson",
        data: dataRef.current as unknown as GeoJSON.FeatureCollection,
      });
    }

    if (!map.getLayer(CIRCLE_LAYER_ID)) {
      map.addLayer({
        id: CIRCLE_LAYER_ID,
        type: "circle",
        source: SOURCE_ID,
        // No minzoom — sim cams are an 8-feature set and we want them
        // visible at the city-wide overview too, so the demo always
        // has something to point at.
        paint: {
          "circle-color": "#22c55e",
          "circle-stroke-color": "#052e16",
          "circle-stroke-width": 1.2,
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            8,
            3,
            12,
            5,
            16,
            7.5,
          ],
          "circle-opacity": 0.95,
        },
      } satisfies maplibregl.CircleLayerSpecification);
    }

    const onClick = (e: maplibregl.MapMouseEvent) => {
      if (useApp.getState().drawMode !== "idle") return;
      const feats = map.queryRenderedFeatures(e.point, {
        layers: [CIRCLE_LAYER_ID],
      });
      const f = feats[0];
      if (!f) return;
      const coords = (f.geometry as GeoJSON.Point).coordinates as [
        number,
        number,
      ];
      popupRef.current?.remove();
      const popup = new maplibreglRuntime.Popup({
        closeButton: true,
        closeOnClick: true,
        maxWidth: "380px",
        offset: 10,
        className: "sim-cam-popup-container",
      })
        .setLngLat(coords)
        .setHTML(popupHtml(f.properties ?? {}))
        .addTo(map);
      popupRef.current = popup;

      // Wire the fullscreen button. The popup's HTML is set via innerHTML
      // (MapLibre's setHTML) so we can't bind a React handler — we have
      // to query the popup's DOM after it's mounted and attach a
      // listener manually. Esc-to-exit is handled natively by the browser.
      const popupEl = popup.getElement();
      const fsBtn = popupEl?.querySelector<HTMLButtonElement>(
        ".sim-cam-popup__fs",
      );
      const iframe = popupEl?.querySelector<HTMLIFrameElement>(
        ".sim-cam-popup__feed iframe",
      );
      if (fsBtn && iframe) {
        fsBtn.addEventListener("click", (ev) => {
          ev.preventDefault();
          ev.stopPropagation();
          // Prefer fullscreen on the iframe so the MediaMTX player's own
          // controls remain reachable when the user exits. Some browsers
          // (older Safari) only expose webkitRequestFullscreen.
          const target = iframe as HTMLIFrameElement & {
            webkitRequestFullscreen?: () => Promise<void>;
          };
          const req =
            target.requestFullscreen ?? target.webkitRequestFullscreen;
          req?.call(target).catch(() => {
            /* user-gesture or permissions-policy refused — silent */
          });
        });
      }
    };
    map.on("click", CIRCLE_LAYER_ID, onClick);

    return () => {
      try {
        map.off("click", CIRCLE_LAYER_ID, onClick);
      } catch {
        /* map already torn down */
      }
      popupRef.current?.remove();
      popupRef.current = null;
      try {
        if (map.getLayer(CIRCLE_LAYER_ID)) map.removeLayer(CIRCLE_LAYER_ID);
        if (map.getSource(SOURCE_ID)) map.removeSource(SOURCE_ID);
      } catch {
        /* same */
      }
    };
  }, [map]);

  return null;
}
